name: try build in ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install depend
      run: sudo apt install clang libclang-9-dev
    - name: clone submodule
      run: git submodule update --init --recursive
    - name: cmake generate
      run: cmake -H. -Bbuild/Debug
    - name: make
      run: make -C build/Debug -j
